import {
  CateringEvent,
  StockItem,
  Client,
  Quotation,
  Transaction,
  BusinessProfile,
} from "./types";

export const initialBusinessProfile: BusinessProfile = {
  name: "ROLEX Events & Caterers",
  tagline: "Exquisite Banquets & Royal Culinary Experiences",
  phone: "+91 98470 12345",
  email: "operations@rolexcaterers.com",
  address: "Rolex Heritage Grand Tower, Calicut Road, Kerala, India",
  gstNumber: "32AAAAA0000A1Z5",
  currencySymbol: "₹",
  quotationTerms: [
    "50% advance payment required upon quotation confirmation.",
    "40% payment payable 48 hours prior to the event setup.",
    "Balance 10% upon successful event conclusion.",
    "Guest count must be locked 3 days prior to the function.",
    "All broken or missing crockery/cutlery will be billed at actual cost.",
  ],
  whatsappTemplate:
    "Dear {clientName}, greetings from ROLEX Events & Caterers! Here is the latest update for your upcoming event '{eventTitle}' on {eventDate}. Please review the details or reach out for any customizations. Warm regards, Rolex Operations Team.",
};

export const initialClients: Client[] = [
  {
    id: "cli-1",
    name: "Dr. Tariq Rahman",
    phone: "+91 98951 44220",
    email: "dr.tariq@rahmanhealth.com",
    address: "Skyline Imperial Villa 14, Kozhikode",
    company: "Rahman Specialty Hospitals",
    vip: true,
    totalEvents: 3,
    totalSpend: 1450000,
    lastEventDate: "2026-09-26",
    notes: "Very particular about warm dessert presentation and copper handi displays.",
  },
  {
    id: "cli-2",
    name: "Adv. Meera Nambiar",
    phone: "+91 94472 88102",
    email: "meera.nambiar@lexchambers.in",
    address: "Rosewood Gardens, Ernakulam",
    company: "Lex Chambers & Associates",
    vip: false,
    totalEvents: 1,
    totalSpend: 480000,
    lastEventDate: "2026-10-04",
    notes: "Requires strictly 100% vegetarian live counters with Jain options.",
  },
  {
    id: "cli-3",
    name: "Sanjay Singhania",
    phone: "+91 98200 99341",
    email: "sanjay@singhanialogistics.com",
    address: "Silver Crest Penthouse, Marine Drive, Kochi",
    company: "Singhania Logistics Ltd",
    vip: true,
    totalEvents: 4,
    totalSpend: 2800000,
    lastEventDate: "2026-09-24",
    notes: "VIP corporate partner. Always requests executive silver service & live mocktail station.",
  },
  {
    id: "cli-4",
    name: "Fathima Nihala",
    phone: "+91 97455 33119",
    email: "nihala.f@gmail.com",
    address: "Palace View Residency, Malappuram",
    vip: false,
    totalEvents: 1,
    totalSpend: 620000,
    lastEventDate: "2026-10-12",
    notes: "Traditional Malabar wedding feast. Demands Dum Biryani cooked on dum woodfire.",
  },
  {
    id: "cli-5",
    name: "Capt. Rajesh Varma",
    phone: "+91 94960 77331",
    email: "capt.varma@maritime.org",
    company: "Maritime Operations",
    address: "Heritage Enclave, Fort Kochi",
    vip: false,
    totalEvents: 2,
    totalSpend: 740000,
    lastEventDate: "2026-08-15",
    notes: "Prefers colonial high tea and seafood grilled appetizers.",
  },
];

export const initialStockItems: StockItem[] = [
  {
    id: "stk-1",
    name: "Royal Brass Chafing Dish (Round 6L)",
    category: "Chafing Dishes",
    totalQty: 45,
    reservedQty: 38,
    unit: "units",
    location: "Aisle A-01, Warehouse 1",
    minThreshold: 10,
    condition: "Excellent",
  },
  {
    id: "stk-2",
    name: "Hammered Copper Handi with Stand",
    category: "Chafing Dishes",
    totalQty: 30,
    reservedQty: 32, // Intentional shortage showcase for upcoming wedding!
    unit: "units",
    location: "Aisle A-03, Warehouse 1",
    minThreshold: 8,
    condition: "Excellent",
  },
  {
    id: "stk-3",
    name: "Rectangular Roll-Top Stainless Chafing Set (9L)",
    category: "Chafing Dishes",
    totalQty: 60,
    reservedQty: 40,
    unit: "units",
    location: "Aisle A-02, Warehouse 1",
    minThreshold: 15,
    condition: "Excellent",
  },
  {
    id: "stk-4",
    name: "Fine Bone China Gold Rim Dinner Plate",
    category: "Crockery & Glassware",
    totalQty: 800,
    reservedQty: 650,
    unit: "pcs",
    location: "Bay B-01, Fragile Storage",
    minThreshold: 150,
    condition: "Excellent",
  },
  {
    id: "stk-5",
    name: "Crystal Cut Water & Juice Goblets",
    category: "Crockery & Glassware",
    totalQty: 900,
    reservedQty: 750,
    unit: "pcs",
    location: "Bay B-03, Fragile Storage",
    minThreshold: 200,
    condition: "Good",
  },
  {
    id: "stk-6",
    name: "Porcelain Dessert Bowls & Platters",
    category: "Crockery & Glassware",
    totalQty: 650,
    reservedQty: 450,
    unit: "pcs",
    location: "Bay B-04, Fragile Storage",
    minThreshold: 100,
    condition: "Excellent",
  },
  {
    id: "stk-7",
    name: "Heavy Silver Finish Dinner Spoon & Fork Set",
    category: "Silverware & Cutlery",
    totalQty: 1000,
    reservedQty: 800,
    unit: "sets",
    location: "Secured Vault C-01",
    minThreshold: 200,
    condition: "Excellent",
  },
  {
    id: "stk-8",
    name: "Antique Brass Dessert & Fruit Spoons",
    category: "Silverware & Cutlery",
    totalQty: 500,
    reservedQty: 350,
    unit: "pcs",
    location: "Secured Vault C-02",
    minThreshold: 100,
    condition: "Good",
  },
  {
    id: "stk-9",
    name: "Live Tandoor Drum Unit with Gas Burner",
    category: "Live Cooking Counters",
    totalQty: 8,
    reservedQty: 6,
    unit: "units",
    location: "Yard Bay D-01",
    minThreshold: 2,
    condition: "Good",
  },
  {
    id: "stk-10",
    name: "Teppanyaki Iron Griddle Live Stall",
    category: "Live Cooking Counters",
    totalQty: 6,
    reservedQty: 4,
    unit: "units",
    location: "Yard Bay D-02",
    minThreshold: 2,
    condition: "Excellent",
  },
  {
    id: "stk-11",
    name: "Live Chaat & Pani Puri Brass Uruli Stall",
    category: "Live Cooking Counters",
    totalQty: 10,
    reservedQty: 8,
    unit: "units",
    location: "Yard Bay D-03",
    minThreshold: 2,
    condition: "Excellent",
  },
  {
    id: "stk-12",
    name: "Ivory Jacquard Banquet Table Cloth (120x80)",
    category: "Linens & Tableware",
    totalQty: 120,
    reservedQty: 95,
    unit: "pcs",
    location: "Linen Room E-01",
    minThreshold: 25,
    condition: "Excellent",
  },
  {
    id: "stk-13",
    name: "Champagne Gold Satin Table Runners",
    category: "Linens & Tableware",
    totalQty: 150,
    reservedQty: 110,
    unit: "pcs",
    location: "Linen Room E-02",
    minThreshold: 30,
    condition: "Excellent",
  },
  {
    id: "stk-14",
    name: "Embroidered Cloth Napkins (Gold Monogram)",
    category: "Linens & Tableware",
    totalQty: 1200,
    reservedQty: 900,
    unit: "pcs",
    location: "Linen Room E-03",
    minThreshold: 200,
    condition: "Good",
  },
  {
    id: "stk-15",
    name: "Insulated Food Pan Carrier Boxes (Camtainers)",
    category: "Warmers & Transport",
    totalQty: 24,
    reservedQty: 20,
    unit: "units",
    location: "Loading Dock F-01",
    minThreshold: 5,
    condition: "Excellent",
  },
  {
    id: "stk-16",
    name: "Commercial Electrical Bain-Marie Warmer",
    category: "Warmers & Transport",
    totalQty: 12,
    reservedQty: 8,
    unit: "units",
    location: "Loading Dock F-02",
    minThreshold: 3,
    condition: "Good",
  },
  {
    id: "stk-17",
    name: "Heavy Duty Stainless Beverage Dispensers (15L)",
    category: "Warmers & Transport",
    totalQty: 20,
    reservedQty: 14,
    unit: "units",
    location: "Loading Dock F-03",
    minThreshold: 4,
    condition: "Excellent",
  },
  {
    id: "stk-18",
    name: "Traditional Brass Nilavilakku Welcome Lamps (5ft)",
    category: "Linens & Tableware",
    totalQty: 8,
    reservedQty: 6,
    unit: "pairs",
    location: "Heritage Room H-01",
    minThreshold: 2,
    condition: "Excellent",
  },
];

export const initialEvents: CateringEvent[] = [
  {
    id: "evt-101",
    title: "Grand Royal Wedding Banquet: Tariq & Zoya",
    clientName: "Dr. Tariq Rahman",
    clientPhone: "+91 98951 44220",
    clientEmail: "dr.tariq@rahmanhealth.com",
    date: "2026-09-26",
    time: "06:30 PM - 11:30 PM",
    venue: "The Grand Regal Palace Convention Centre, Calicut",
    guestCount: 500,
    eventType: "Wedding",
    status: "confirmed",
    packageTier: "Royal Grandeur",
    budget: 825000,
    advancePaid: 450000,
    specialInstructions:
      "Strict VIP dining protocol. Royal Dum Biryani must be plated directly from sealed clay degh pots.",
    createdAt: "2026-09-15T10:00:00Z",
    readinessChecklist: [
      {
        id: "chk-1",
        label: "Client Contract & 50% Advance Received",
        category: "client",
        completed: true,
      },
      {
        id: "chk-2",
        label: "Final Banquet Menu Locked & Approved",
        category: "menu",
        completed: true,
      },
      {
        id: "chk-3",
        label: "Equipment & Chafing Dish Allocation Verified",
        category: "stock",
        completed: false, // Shortage pending
        notes: "Shortage of 2 Hammered Copper Handis detected!",
      },
      {
        id: "chk-4",
        label: "Head Chef & Banquet Team Scheduled",
        category: "staff",
        completed: true,
      },
      {
        id: "chk-5",
        label: "Raw Meat & Exotic Spices Delivery Confirmed",
        category: "menu",
        completed: true,
      },
      {
        id: "chk-6",
        label: "Logistics Truck Departure Time Set",
        category: "logistics",
        completed: false,
      },
      {
        id: "chk-7",
        label: "Second Milestone Payment (40%) Collected",
        category: "payment",
        completed: false,
      },
    ],
    menuCourses: [
      {
        category: "Welcome Drinks",
        items: [
          {
            id: "m-1",
            name: "Royal Saffron Almond Sharbat",
            isVeg: true,
            description: "Chilled badam milk infused with Kashmir saffron",
            estimatedPortions: 550,
          },
          {
            id: "m-2",
            name: "Fresh Mint & Passionfruit Cooler",
            isVeg: true,
            description: "Crushed mint with sparkling tropical nectar",
            estimatedPortions: 400,
          },
        ],
      },
      {
        category: "Starters & Appetizers",
        items: [
          {
            id: "m-3",
            name: "Murgh Malai Reshmi Kebab",
            isVeg: false,
            description: "Creamy tandoori chicken glazed with melted butter",
            estimatedPortions: 500,
          },
          {
            id: "m-4",
            name: "Peshawari Mutton Seekh Kebab",
            isVeg: false,
            description: "Spiced minced lamb roasted on skewers",
            estimatedPortions: 450,
          },
          {
            id: "m-5",
            name: "Paneer Angara Tikka",
            isVeg: true,
            description: "Smoked cottage cheese infused with charcoal aroma",
            estimatedPortions: 250,
          },
        ],
      },
      {
        category: "Main Course",
        items: [
          {
            id: "m-6",
            name: "Rolex Heritage Dum Mutton Biryani",
            isVeg: false,
            description: "Long-grain aged basmati layered with succulent goat meat & whole spices",
            estimatedPortions: 550,
          },
          {
            id: "m-7",
            name: "Murgh Mughlai Korma with Fried Cashews",
            isVeg: false,
            description: "Velvety braised chicken gravy in white onion paste",
            estimatedPortions: 400,
          },
          {
            id: "m-8",
            name: "Dal Makhani Handi Se",
            isVeg: true,
            description: "Slow-simmered black lentils cooked overnight with cream",
            estimatedPortions: 300,
          },
          {
            id: "m-9",
            name: "Assorted Bread Basket (Butter Naan & Sheermal)",
            isVeg: true,
            description: "Freshly pulled from live tandoor drums",
            estimatedPortions: 800,
          },
        ],
      },
      {
        category: "Desserts & Sweets",
        items: [
          {
            id: "m-10",
            name: "Shahi Tukda with Gold Varq & Rabri",
            isVeg: true,
            description: "Crispy ghee-toasted bread steeped in thickened saffron milk",
            estimatedPortions: 450,
          },
          {
            id: "m-11",
            name: "Warm Angoori Gulab Jamun",
            isVeg: true,
            description: "Bite-sized dumplings served in green cardamom syrup",
            estimatedPortions: 450,
          },
        ],
      },
    ],
    stockAllocations: [
      {
        stockItemId: "stk-1",
        stockItemName: "Royal Brass Chafing Dish (Round 6L)",
        quantity: 20,
        status: "reserved",
      },
      {
        stockItemId: "stk-2",
        stockItemName: "Hammered Copper Handi with Stand",
        quantity: 18,
        status: "shortage",
        shortageQty: 2,
      },
      {
        stockItemId: "stk-4",
        stockItemName: "Fine Bone China Gold Rim Dinner Plate",
        quantity: 500,
        status: "reserved",
      },
      {
        stockItemId: "stk-7",
        stockItemName: "Heavy Silver Finish Dinner Spoon & Fork Set",
        quantity: 500,
        status: "reserved",
      },
      {
        stockItemId: "stk-9",
        stockItemName: "Live Tandoor Drum Unit with Gas Burner",
        quantity: 4,
        status: "reserved",
      },
    ],
    staffAssigned: [
      {
        id: "st-1",
        name: "Chef Ibrahim Qureshi",
        role: "Lead Chef",
        phone: "+91 98460 11990",
      },
      {
        id: "st-2",
        name: "Rashid V.K.",
        role: "Banquet Manager",
        phone: "+91 97444 88312",
      },
      {
        id: "st-3",
        name: "Pradeep Menon",
        role: "Floor Supervisor",
        phone: "+91 98471 22891",
      },
    ],
    expenses: [
      {
        id: "exp-1",
        eventId: "evt-101",
        eventTitle: "Grand Royal Wedding Banquet: Tariq & Zoya",
        date: "2026-09-20",
        category: "Raw Materials & Groceries",
        description: "Procurement of 120kg Prime Tender Goat & Aged Biryani Rice",
        amount: 145000,
        paidTo: "Royal Meat Traders & Al-Hind Spices",
        paymentMethod: "Bank Transfer",
      },
      {
        id: "exp-2",
        eventId: "evt-101",
        eventTitle: "Grand Royal Wedding Banquet: Tariq & Zoya",
        date: "2026-09-21",
        category: "Equipment & Fuel",
        description: "Commercial LPG cylinders & Tandoor Charcoal sacks",
        amount: 18500,
        paidTo: "Calicut Gas Agencies",
        paymentMethod: "UPI",
      },
    ],
  },
  {
    id: "evt-102",
    title: "Singhania Logistics Annual Executive Gala",
    clientName: "Sanjay Singhania",
    clientPhone: "+91 98200 99341",
    clientEmail: "sanjay@singhaniatech.com",
    date: "2026-09-24", // Immediate tomorrow!
    time: "07:30 PM - 11:00 PM",
    venue: "Le Maritime Ballroom, Willingdon Island, Kochi",
    guestCount: 220,
    eventType: "Corporate Gala",
    status: "confirmed",
    packageTier: "Imperial Gold",
    budget: 440000,
    advancePaid: 350000,
    specialInstructions: "High-level board members attending. Silver butler pass-around service required.",
    createdAt: "2026-09-12T14:30:00Z",
    readinessChecklist: [
      {
        id: "chk-21",
        label: "Corporate Agreement Signed & Advance Cleared",
        category: "client",
        completed: true,
      },
      {
        id: "chk-22",
        label: "Gourmet Continental & Indian Fusion Menu Locked",
        category: "menu",
        completed: true,
      },
      {
        id: "chk-23",
        label: "Crockery & Crystal Glassware Packed in Crates",
        category: "stock",
        completed: true,
      },
      {
        id: "chk-24",
        label: "Butler Staff Uniformed & Briefed",
        category: "staff",
        completed: true,
      },
      {
        id: "chk-25",
        label: "Refrigerated Van Ready for Departure at 3:00 PM",
        category: "logistics",
        completed: true,
      },
      {
        id: "chk-26",
        label: "Final Invoice Generated & Corporate PO Received",
        category: "payment",
        completed: true,
      },
    ],
    menuCourses: [
      {
        category: "Welcome Drinks",
        items: [
          {
            id: "m-20",
            name: "Smoked Cranberry & Rosemary Spritzer",
            isVeg: true,
            description: "Craft botanical fizz served in champagne flutes",
            estimatedPortions: 240,
          },
        ],
      },
      {
        category: "Starters & Appetizers",
        items: [
          {
            id: "m-21",
            name: "Malabar Pepper Prawns Tartlets",
            isVeg: false,
            description: "Jumbo prawns sautéed in shallots and crushed black peppercorn",
            estimatedPortions: 250,
          },
          {
            id: "m-22",
            name: "Truffle Mushroom Bruschetta",
            isVeg: true,
            description: "Wild sauteed forest mushrooms on toasted sourdough",
            estimatedPortions: 220,
          },
        ],
      },
      {
        category: "Main Course",
        items: [
          {
            id: "m-23",
            name: "Pan-Seared Sea Bass with Lemon Caper Beurre Blanc",
            isVeg: false,
            description: "Fresh catch served over herb-infused roasted baby potatoes",
            estimatedPortions: 200,
          },
          {
            id: "m-24",
            name: "Awadhi Murgh Biryani",
            isVeg: false,
            description: "Gentle aromatic spices cooked in sealed brass cauldrons",
            estimatedPortions: 200,
          },
        ],
      },
      {
        category: "Desserts & Sweets",
        items: [
          {
            id: "m-25",
            name: "Belgian Dark Chocolate Soufflé with Salted Caramel",
            isVeg: true,
            description: "Warm molten center accompanied by Madagascar vanilla gelato",
            estimatedPortions: 220,
          },
        ],
      },
    ],
    stockAllocations: [
      {
        stockItemId: "stk-3",
        stockItemName: "Rectangular Roll-Top Stainless Chafing Set (9L)",
        quantity: 12,
        status: "reserved",
      },
      {
        stockItemId: "stk-5",
        stockItemName: "Crystal Cut Water & Juice Goblets",
        quantity: 250,
        status: "reserved",
      },
      {
        stockItemId: "stk-7",
        stockItemName: "Heavy Silver Finish Dinner Spoon & Fork Set",
        quantity: 250,
        status: "reserved",
      },
    ],
    staffAssigned: [
      {
        id: "st-10",
        name: "Chef Anthony Paul",
        role: "Lead Chef",
        phone: "+91 98470 55112",
      },
      {
        id: "st-11",
        name: "Shyam Sundar",
        role: "Floor Supervisor",
        phone: "+91 94471 99003",
      },
    ],
    expenses: [
      {
        id: "exp-11",
        eventId: "evt-102",
        eventTitle: "Singhania Logistics Annual Executive Gala",
        date: "2026-09-22",
        category: "Raw Materials & Groceries",
        description: "Imported Norwegian Sea Bass & Truffle Oils",
        amount: 88000,
        paidTo: "Oceanic Seafoods Co.",
        paymentMethod: "Bank Transfer",
      },
      {
        id: "exp-12",
        eventId: "evt-102",
        eventTitle: "Singhania Logistics Annual Executive Gala",
        date: "2026-09-23",
        category: "Staff Wages",
        description: "VIP Uniformed Butler crew wages (12 staff)",
        amount: 36000,
        paidTo: "Elite Hospitality Staffing",
        paymentMethod: "Bank Transfer",
      },
    ],
  },
  {
    id: "evt-103",
    title: "Adv. Meera Nambiar Golden Jubilee Banquet",
    clientName: "Adv. Meera Nambiar",
    clientPhone: "+91 94472 88102",
    clientEmail: "meera.nambiar@lexchambers.in",
    date: "2026-10-04",
    time: "11:30 AM - 03:30 PM",
    venue: "Taj Gateway Emerald Hall, Marine Drive",
    guestCount: 300,
    eventType: "Birthday / Jubilee",
    status: "confirmed",
    packageTier: "Classic Elegance",
    budget: 480000,
    advancePaid: 200000,
    specialInstructions: "100% pure vegetarian Kerala traditional Sadhya fusion banquet served on brass urulis.",
    createdAt: "2026-09-18T09:00:00Z",
    readinessChecklist: [
      {
        id: "chk-31",
        label: "Client Advance 50% Verified",
        category: "client",
        completed: true,
      },
      {
        id: "chk-32",
        label: "Traditional Sadhya Menu Breakdown Locked",
        category: "menu",
        completed: true,
      },
      {
        id: "chk-33",
        label: "Brass Urulis & Plantain Leaf Sourcing",
        category: "stock",
        completed: false,
      },
      {
        id: "chk-34",
        label: "Traditional Brahmin Master Chefs Assigned",
        category: "staff",
        completed: false,
      },
      {
        id: "chk-35",
        label: "Transport Schedule Locked",
        category: "logistics",
        completed: false,
      },
    ],
    menuCourses: [
      {
        category: "Welcome Drinks",
        items: [
          {
            id: "m-31",
            name: "Tender Coconut Sambharam with Crushed Bird's Eye Chili",
            isVeg: true,
            description: "Cooling natural elixir with shallots, curry leaves & ginger",
            estimatedPortions: 320,
          },
        ],
      },
      {
        category: "Main Course",
        items: [
          {
            id: "m-32",
            name: "Royal Kerala Sadhya (24 Curries, Avial, Thoran, Olan, Kalan)",
            isVeg: true,
            description: "Authentic royal feast served on traditional brass vessels",
            estimatedPortions: 320,
          },
          {
            id: "m-33",
            name: "Palada Pradhaman & Parippu Payasam",
            isVeg: true,
            description: "Slow-steamed rice flakes simmered in rich condensed milk",
            estimatedPortions: 350,
          },
        ],
      },
    ],
    stockAllocations: [
      {
        stockItemId: "stk-18",
        stockItemName: "Traditional Brass Nilavilakku Welcome Lamps (5ft)",
        quantity: 4,
        status: "reserved",
      },
      {
        stockItemId: "stk-11",
        stockItemName: "Live Chaat & Pani Puri Brass Uruli Stall",
        quantity: 4,
        status: "reserved",
      },
    ],
    staffAssigned: [],
    expenses: [],
  },
  {
    id: "evt-104",
    title: "Malabar Heritage Feast: Nihala Engagement",
    clientName: "Fathima Nihala",
    clientPhone: "+91 97455 33119",
    clientEmail: "nihala.f@gmail.com",
    date: "2026-10-12",
    time: "12:00 PM - 05:00 PM",
    venue: "Al-Reem Royal Convention Center, Malappuram",
    guestCount: 400,
    eventType: "Reception",
    status: "draft",
    packageTier: "Custom Executive",
    budget: 620000,
    advancePaid: 0,
    specialInstructions: "Client requested quotation review before confirming booking.",
    createdAt: "2026-09-22T16:00:00Z",
    readinessChecklist: [
      {
        id: "chk-41",
        label: "Quotation Awaiting Client Signature",
        category: "client",
        completed: false,
      },
      {
        id: "chk-42",
        label: "Draft Menu Customization Sent",
        category: "menu",
        completed: true,
      },
      {
        id: "chk-43",
        label: "Equipment Hold Placed",
        category: "stock",
        completed: false,
      },
    ],
    menuCourses: [],
    stockAllocations: [],
    staffAssigned: [],
    expenses: [],
  },
];

export const initialQuotations: Quotation[] = [
  {
    id: "quot-101",
    quotationNumber: "ROX-2026-089",
    eventId: "evt-101",
    eventTitle: "Grand Royal Wedding Banquet: Tariq & Zoya",
    clientName: "Dr. Tariq Rahman",
    clientPhone: "+91 98951 44220",
    clientEmail: "dr.tariq@rahmanhealth.com",
    date: "2026-09-16",
    validUntil: "2026-09-26",
    subtotal: 750000,
    discountPercentage: 5,
    taxPercentage: 18,
    total: 840750,
    status: "approved",
    items: [
      {
        id: "qi-1",
        description: "Royal Grandeur 5-Course Banquet Feast (Per Plate rate)",
        category: "Food & Beverage",
        qty: 500,
        unitPrice: 1250,
        amount: 625000,
      },
      {
        id: "qi-2",
        description: "Live Tandoor & Charcoal Kebab Cooking Counter Setup",
        category: "Live Stations",
        qty: 2,
        unitPrice: 25000,
        amount: 50000,
      },
      {
        id: "qi-3",
        description: "Gold Rim Fine Bone China & Heavy Silver Cutlery Service",
        category: "Tableware",
        qty: 500,
        unitPrice: 90,
        amount: 45000,
      },
      {
        id: "qi-4",
        description: "VIP Uniformed Service Team & Banquet Supervisors",
        category: "Service & Hospitality",
        qty: 1,
        unitPrice: 30000,
        amount: 30000,
      },
    ],
    notes: "Special 5% loyalty discount applied for Rahman Health VIP relationship.",
  },
  {
    id: "quot-102",
    quotationNumber: "ROX-2026-090",
    eventId: "evt-102",
    eventTitle: "Singhania Logistics Annual Executive Gala",
    clientName: "Sanjay Singhania",
    clientPhone: "+91 98200 99341",
    clientEmail: "sanjay@singhaniatech.com",
    date: "2026-09-13",
    validUntil: "2026-09-24",
    subtotal: 400000,
    discountPercentage: 0,
    taxPercentage: 18,
    total: 472000,
    status: "approved",
    items: [
      {
        id: "qi-11",
        description: "Imperial Gold 4-Course Continental & Fusion Dinner",
        category: "Food & Beverage",
        qty: 220,
        unitPrice: 1450,
        amount: 319000,
      },
      {
        id: "qi-12",
        description: "Silver Butler Cocktail Pass-Around & Glassware Setup",
        category: "Service",
        qty: 1,
        unitPrice: 45000,
        amount: 45000,
      },
      {
        id: "qi-13",
        description: "Refrigerated Van Transportation & Island Logistics",
        category: "Logistics",
        qty: 1,
        unitPrice: 36000,
        amount: 36000,
      },
    ],
  },
  {
    id: "quot-104",
    quotationNumber: "ROX-2026-092",
    eventId: "evt-104",
    eventTitle: "Malabar Heritage Feast: Nihala Engagement",
    clientName: "Fathima Nihala",
    clientPhone: "+91 97455 33119",
    clientEmail: "nihala.f@gmail.com",
    date: "2026-09-22",
    validUntil: "2026-09-29",
    subtotal: 580000,
    discountPercentage: 3,
    taxPercentage: 18,
    total: 663868,
    status: "sent",
    items: [
      {
        id: "qi-41",
        description: "Authentic Dum Biryani Malabar Wedding Feast",
        category: "Food & Beverage",
        qty: 400,
        unitPrice: 1200,
        amount: 480000,
      },
      {
        id: "qi-42",
        description: "Heritage Dessert Stall with Sulaimani & Halwa Platter",
        category: "Desserts",
        qty: 400,
        unitPrice: 150,
        amount: 60000,
      },
      {
        id: "qi-43",
        description: "Transportation to Malappuram & Banquet Setup",
        category: "Logistics",
        qty: 1,
        unitPrice: 40000,
        amount: 40000,
      },
    ],
  },
];

export const initialTransactions: Transaction[] = [
  {
    id: "txn-1",
    date: "2026-09-17",
    type: "income",
    amount: 450000,
    category: "Event Advance Payment",
    description: "50% Advance for Tariq & Zoya Wedding",
    eventId: "evt-101",
    eventTitle: "Grand Royal Wedding Banquet: Tariq & Zoya",
    clientName: "Dr. Tariq Rahman",
    paymentMethod: "Bank Transfer",
    status: "completed",
  },
  {
    id: "txn-2",
    date: "2026-09-14",
    type: "income",
    amount: 350000,
    category: "Event Advance Payment",
    description: "Corporate Advance for Singhania Annual Gala",
    eventId: "evt-102",
    eventTitle: "Singhania Logistics Annual Executive Gala",
    clientName: "Sanjay Singhania",
    paymentMethod: "Bank Transfer",
    status: "completed",
  },
  {
    id: "txn-3",
    date: "2026-09-19",
    type: "income",
    amount: 200000,
    category: "Event Advance Payment",
    description: "Advance token for Adv. Meera Nambiar Jubilee",
    eventId: "evt-103",
    eventTitle: "Adv. Meera Nambiar Golden Jubilee Banquet",
    clientName: "Adv. Meera Nambiar",
    paymentMethod: "UPI",
    status: "completed",
  },
  {
    id: "txn-4",
    date: "2026-09-20",
    type: "expense",
    amount: 145000,
    category: "Raw Materials & Groceries",
    description: "Procurement of 120kg Prime Tender Goat & Aged Biryani Rice",
    eventId: "evt-101",
    eventTitle: "Grand Royal Wedding Banquet: Tariq & Zoya",
    paymentMethod: "Bank Transfer",
    status: "completed",
  },
  {
    id: "txn-5",
    date: "2026-09-21",
    type: "expense",
    amount: 18500,
    category: "Equipment & Fuel",
    description: "Commercial LPG cylinders & Tandoor Charcoal sacks",
    eventId: "evt-101",
    eventTitle: "Grand Royal Wedding Banquet: Tariq & Zoya",
    paymentMethod: "UPI",
    status: "completed",
  },
  {
    id: "txn-6",
    date: "2026-09-22",
    type: "expense",
    amount: 88000,
    category: "Raw Materials & Groceries",
    description: "Imported Norwegian Sea Bass & Truffle Oils",
    eventId: "evt-102",
    eventTitle: "Singhania Logistics Annual Executive Gala",
    paymentMethod: "Bank Transfer",
    status: "completed",
  },
  {
    id: "txn-7",
    date: "2026-09-23",
    type: "expense",
    amount: 36000,
    category: "Staff Wages",
    description: "VIP Uniformed Butler crew wages (12 staff)",
    eventId: "evt-102",
    eventTitle: "Singhania Logistics Annual Executive Gala",
    paymentMethod: "Bank Transfer",
    status: "completed",
  },
];
